#!/bin/sh

##############################################################################
# Gradle start up script for POSIX generated by Gradle.
##############################################################################

APP_NAME="Gradle"
APP_BASE_NAME=${0##*/}

GRADLE_USER_HOME="${GRADLE_USER_HOME:-$HOME/.gradle}"

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

case "$(uname)" in
    CYGWIN* | MINGW* | MSYS* )
        cygwin=true
        ;;
esac

APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || die "Cannot determine application directory"

DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

exec "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" "$@"
