name: Release Source JAR

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Create source JAR
        run: |
          mkdir -p release
          zip -r release/meteor-modules-sources.jar src README.md || true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/meteor-modules-sources.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
