name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Package source JAR
        run: |
          mkdir -p build/libs
          cd src && zip -r ../build/libs/meteor-modules-${{ github.ref_name }}-sources.jar . && cd ..

      - name: Upload JAR artifacts
        uses: actions/upload-artifact@v4
        with:
          name: meteor-modules-jars
          path: build/libs/*.jar

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/libs/*.jar
          body: |
            # Meteor Modules ${{ github.ref_name }}
            
            AI-powered automation modules for Meteor Client with:
            - Pathfinding-enabled bots (GardenBot, TorchGridBot, WarehouseBot)
            - Legit behavior (human-like pacing, LOS checks, movement)
            - Advanced AI systems (behavior trees, ML integration)
            
            **Note**: This release contains source code. A full compiled JAR requires resolving API dependencies with the latest Meteor Client version.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
